version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.2}-v4-fpm
    environment:
      PHP_EXTENSIONS: gd
      TYPO3_VERSION: ${TYPO3_VERSION:-^10.4}
      TYPO3_ORG_PASSWORD:
      TYPO3_ORG_USERNAME:
      typo3DatabaseHost: mysql
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql
