version: '3.9'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v4-cli
    environment:
      PHP_EXTENSIONS: gd
      TYPO3_VERSION: ${TYPO3_VERSION:-^10.4}
      TYPO3_API_PASSWORD:
      TYPO3_API_USERNAME:
      typo3DatabaseName: typo3_functional
      typo3DatabaseHost: mysql
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql
